### ISSUE TITLE
Call unregisterPublisher on rosmaster RPC API when last Publisher handle is destroyed

### ISSUE THREAD

**Issue by ssnover** [Carter12s/roslibrust#112]
rosmaster may assume this when the node destructs, but would be good and proper to call this to unregister the publisher.

**Comment by Carter12s** [comment]
Would be interested in traffic snooping on a ros1 cpp node and ros1 python node and seeing what their behavior is.

While it might be "proper" to unregister. I think "best" is to copy what the "standard" clients do as closely as possible.

My money is on different behavior between the two of them...

**Comment by ssnover** [comment]
Can't wait to rewrite rosmaster so that it's easier to capture existing client behavior 😁
