### ISSUE TITLE
ROS 2 support

### ISSUE THREAD

**Issue by MatteoMariano** [Carter12s/roslibrust#145]
Hi there!
What is already supported for ROS2 and when you think that pub/sub for ROS2 will be released? 
Thanks

**Comment by Carter12s** [comment]
Heyo!

So sorry this is a little messy and a little complicated, and our documentation isn't super clear. If you have a chance and are interested in getting this cleared up I'd recommend watching: https://vimeo.com/879001716/ddf60792e8 to better understand what is going on.

Current state as of today:

- Using [rosbridge_server](https://github.com/RobotWebTools/rosbridge_suite/blob/ros2/README.md) in ROS2 all library functionality is supported. Pub, Sub, and services should be fully functional, and our message generation tools are fully capable of reading ROS2 interface files and generating correct Rust types for them.

- We are working on support for ROS1 native communication that doesn't rely on rosbridge_server at the moment, but instead implements ROS1's "[TCPROS](https://wiki.ros.org/ROS/TCPROS)" protocol.

- We are not currently planning supporting ROS2 native communication based on DDS at this time. Although with the announcement that ROS2 will be adding Zenoh as a communication mechanism we may build support for ROS2 native communication with Zenoh in the future.
