### ISSUE TITLE
roslibrust fails to reconnect to a rosbridge

### ISSUE THREAD

**Issue by hwoithe** [Carter12s/roslibrust#152]
A simple subscriber created using roslibrust will fail to reconnect to a rosbridge that is repeatedly brought up and down.

To reproduce:

terminal 1: ```roscore```
terminal 2: ```rosrun rosbridge_server rosbridge_websocket```
terminal 3: ```rostopic pub -r 10 /talker std_msgs/Header '{stamp: now, frame_id: "frame_id"}'```
terminal 4 (in roslibrust root): ```cargo run --example subscribe_and_log```

Bring the rosbridge down and back up while keeping everything else running. The subscriber will not be able to receive messages from the publisher.

I believe that the RwLockReadGuard temporary created in the match's scrutinee stays alive for the entire match.
https://github.com/Carter12s/roslibrust/blob/90ff4ce606fd8e3386df58da0e96235707ab77b9/roslibrust/src/rosbridge/client.rs#L765

The call to client.write() will then block because the match still holds the read lock.
https://github.com/Carter12s/roslibrust/blob/90ff4ce606fd8e3386df58da0e96235707ab77b9/roslibrust/src/rosbridge/client.rs#L770

To showcase this, store the current scrutinee expression into a temporary variable and use the temporary variable in the match as the scrutinee. This should now allow the subscriber to reconnect to a rosbridge that is brought up and down.

**Comment by Carter12s** [comment]
Fantastic report and sleuthing!

I'll replicate and fix, apologies for the delayed response.
