### ISSUE TITLE
Support for rosapi

### ISSUE THREAD

**Issue by Carter12s** [Carter12s/roslibrust#18]
Would be very nice for this library to support:
- rostopic list
- rostopic info
- roservice list
- rosservice info

These calls are available if the rosapi node is being run, we could build a nice wrapper API to abstract away the underlying service calls and nicely wrap the functionality.

**Comment by ssnover** [comment]
If we're going to implement these as libraries, would it make sense to also build binaries so that people can call these from CLI without a ROS distro installed?

**Comment by Carter12s** [comment]
This is complete and will be released with v0.6.0 shortly
