### ISSUE TITLE
Misleading message when calling inactive service

### ISSUE THREAD

**Issue by gcrowards-amp** [Carter12s/roslibrust#88]
```
    let result = client
        .call_service::<(), rosapi::GetTimeResponse>("/not_real_service", ())
        .await
        .expect("Error while calling get_time service");
```

This will panic with the following error instead of gracefully failing: 

> thread 'main' panicked at 'Error while calling get_time service: InvalidMessage(Error("invalid type: string \"Service /not_real_service does not exist\", expected struct GetTimeResponse", line: 0, column: 0))'

**Comment by Carter12s** [comment]
Luckily, a ROS message can't be "just a string" in JSON, it has to be a object containing a field which is a string.

I'm fairly certain that rosbridge_server returns a string when it encounters any error, so we should be able to make a stronger fallback case for "ServerReportedError"

Something like try_parse to expected type, if that fails, try_parse to string, if that succeeds report "ServerReportedError({msg})".

Unfortunately, I don't think we can safely try to parse the error past that to a specific ServiceDoesNotExist error. I think if someone wanted to do that specifically, I would encourage them to use rosapi to check if the service existed ahead of calling...
